global:
  commonAnnotations: {}
  commonLabels: {}

enabled: true

argocd: 
  # Namespace argocd is deployed in
  namespace: argocd
  server: https://kubernetes.default.svc
  # The project the proxies will be deployed in
  project: ingress-proxies

networkPolicy:
  enabled: false
  ingress:
    traefikNamespace: traefik
    traefikPodSelector:
      matchLabels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/instance: traefik

cert:
  # The certificate to use for the ingresses
  reflectedSecret:
    enabled: true
    originNamespace: cert-manager
    originName: example-com-tls

defaults:
  # Some default values for the proxies, can be overridden per proxy
  ingress:
    entrypoint: websecure
    middleware:
      name: traefik-default-chain
      namespace: traefik
  backend: 
    tls:
      skipVerify: false
    protocol: TCP

proxies: []
  # # Entry with all the parameters
  # - name: whoami 
  #   enabled: true
  #   ingress: 
  #     enabled: true 
  #     url: "whoami.frontend.com"
  #     entrypoint: websecure
  #     middleware:
  #       name: traefik-default-chain
  #       namespace: traefik
  #   backend:
  #     # Connection details for the external server
  #     url: "whoami.backend.com"
  #     port: 80
  #     protocol: TCP
  #     # If tls should be enabled
  #     tls:
  #       enabled: false
  #       skipVerify: false
  # # # Another entry with only the required parameters, other parameters will use the defaults
  # - name: another-whoami 
  #   enabled: true
  #   ingress: 
  #     enabled: true 
  #     url: "another-whoami.frontend.com"
  #   backend:
  #     url: "another-whoami.backend.com"
  #     port: 80
  #     tls:
  #       enabled: false
  #       skipVerify: false